version: '3'

services:
  postgres:
    image: postgres:14-bullseye
    container_name: db-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: workive-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./data/db-pg:/data/postgres

